-- AlterTable
ALTER TABLE "EMI" ADD COLUMN "type" TEXT NOT NULL DEFAULT 'FIXED';
ALTER TABLE "EMI" ADD COLUMN "interestRate" DOUBLE PRECISION;
ALTER TABLE "EMI" ADD COLUMN "paidAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "EMI" ALTER COLUMN "emiAmount" DROP NOT NULL;
ALTER TABLE "EMI" ALTER COLUMN "totalInstallments" DROP NOT NULL;
ALTER TABLE "EMI" ALTER COLUMN "nextDueDate" DROP NOT NULL;

-- CreateTable
CREATE TABLE "EMIPayment" (
    "id" TEXT NOT NULL,
    "emiId" TEXT NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "paidAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "note" VARCHAR(500),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EMIPayment_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "EMIPayment_emiId_idx" ON "EMIPayment"("emiId");

-- AddForeignKey
ALTER TABLE "EMIPayment" ADD CONSTRAINT "EMIPayment_emiId_fkey" FOREIGN KEY ("emiId") REFERENCES "EMI"("id") ON DELETE CASCADE ON UPDATE CASCADE;
